### ISSUE TITLE
Example usage for Events

### ISSUE THREAD

**Issue by jpblair** [indeedeng/java-dogstatsd-client#15] opened 2015-07-30 20:37 UTC
Looking at the `StatsDClient` class, I see that there is a `recordEvent()` method which accepts an `Event` as a parameter.  However, the documentation has no usage examples for this, only for metrics.  I've been doing it like this, but the data doesn't seem to be coming through:

`StatsDClient statsd = new NonBlockingStatsDClient( /*  some parameters   */ );`
`Event event = Event.builder().withTitle("title").withText("body").build();`
`statsd.recordEvent(event);`

**Comment by ovesh** [comment] 2015-08-01 20:18
The usage seems correct.
I'll test this locally and see if it works for me.
I'll also add some usage documentation.

**Comment by jpblair** [comment] 2015-08-03 18:50
I've figured out that my issue seems to be upstream with the java-statsd-client - I've added an issue to their Github here:

https://github.com/tim-group/java-statsd-client/issues/35

**Comment by ovesh** [comment] 2015-08-03 21:07
Hmmm sounds like it might be an issue with our code actually. I'll have a look in any case.

**Comment by jpblair** [comment] 2015-08-04 16:35
I tried pushing some metrics using `java-statsd-client` instead and still didn't see any packets being sent, so that's why I figured it might be an issue in their library.  But it's entirely possible that maybe I didn't properly modify the Maven dependency or import or something and was still using your code.  I appreciate the quick responses regardless!

**Comment by ovesh** [comment] 2015-08-06 08:04
I just tried posting an event locally, and it works.
Maybe you have a configuration or network issue over there?
Does posting metrics work? If it does, then I have no idea why you can't post events.

I'm going to close this issue, because I can't reproduce the problem.

**Closed by ovesh** 2015-08-06 08:04 UTC

**Comment by jpblair** [comment] 2015-08-07 13:52
No, cannot post metrics either.  I'm able to post events using another library (https://github.com/arnabk/java-dogstatsd-client) that uses a custom implementation instead of `java-statsd-client`.
